export const SymptomsList = {
    Headache: require('../assets/icons/Headache.png'),
    Fever: require('../assets/icons/fever.png'),
    Nausea: require('../assets/icons/nausea.png'),
    Cold: require('../assets/icons/cold.png'),
    'Mental Health' :require('../assets/icons/MentalHealth.png'),
    Allergies: require('../assets/icons/Allergies.png'),
    Cough: require('../assets/icons/cold.png'),
    Diarrhea: require('../assets/icons/Diarrhea.png'),
    Constipation: require('../assets/icons/Constipation.png'),
    'Eye Problem': require('../assets/icons/Eyeproblem.png'),
    'Joint Problem' :require('../assets/icons/jointProblem.png'),
    'Skin Problem': require('../assets/icons/Skinproblem.png'),
    'Uterus Problem': require('../assets/icons/UterusPain.png'),
}       